name: Unveiled Moments
favicon: null
layout_spectrum: 0.9957101065665483
typography_spectrum: 0.6284495654981583
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#424242'
    - '#d4d4d4'
    - '#777777'
  brandStrength: 0.0625
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0
purpose: []
