name: Unveiled Moments
favicon: null
layout_spectrum: 0.9957101065665483
typography_spectrum: 0.6284495654981583
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4b4442'
    - '#e6d3b2'
    - '#978b83'
    - '#590826'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
